# Generated by Django 2.1.7 on 2019-03-27 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rudumbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice1',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
