# Generated by Django 2.1.7 on 2019-03-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rudumbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='djangosession',
            table='django_session',
        ),
    ]
