# Generated by Django 2.1.7 on 2019-03-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rudumbapp', '0002_auto_20190307_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Quizzes',
            new_name='Quiz',
        ),
        migrations.RenameModel(
            old_name='Stats',
            new_name='Stat',
        ),
    ]
