# Generated by Django 2.1.5 on 2019-03-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rudumbapp', '0002_auto_20190328_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='media/'),
        ),
    ]
