# Generated by Django 2.1.7 on 2019-03-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rudumbapp', '0003_auto_20190307_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='datequizdone',
            new_name='date_quiz_done',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='resultquiz',
            new_name='result_quiz',
        ),
    ]
