# Generated by Django 2.1.5 on 2019-03-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rudumbapp', '0003_auto_20190331_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to=''),
        ),
    ]
