# Generated by Django 2.1.5 on 2019-03-31 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rudumbapp', '0004_auto_20190331_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(default='default.png', upload_to='quizzPictures'),
        ),
    ]
