# Generated by Django 2.1.7 on 2019-03-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rudumbapp', '0005_auto_20190331_1433'),
        ('rudumbapp', '0002_auto_20190327_1054'),
    ]

    operations = [
    ]
